Repository SAP/architecture-center, pull requests merged in 2025-09, with the labels that each got.

#482 Removing contributors
  docs/ref-arch/RA0002/1-fundamentals/readme.md
Labels: ready for review

#479 Updated AI Agents: Content-Based (Joule Studio) vs Code-Based
  docs/ref-arch/RA0005/1-basics/readme.md
  docs/ref-arch/RA0005/2-semantic-search/readme.md
  docs/ref-arch/RA0005/3-retrieval-augmented-generation/readme.md
  docs/ref-arch/RA0005/5-ai-agents/drawio/reference-architecture-generative-ai-code-based.drawio
  docs/ref-arch/RA0005/5-ai-agents/drawio/reference-architecture-generative-ai-content-based.drawio
  docs/ref-arch/RA0005/5-ai-agents/images/Agent_FD.svg
  docs/ref-arch/RA0005/5-ai-agents/readme.md
  docs/ref-arch/RA0005/6-agents-structured-data/drawio/reference-architecture-generative-ai-intelligent-data-apps.drawio
  docs/ref-arch/RA0005/6-agents-structured-data/readme.md
  docs/ref-arch/RA0005/readme.md
Labels: ready for review

#489 Fix broken links for RA0005
  docs/ref-arch/RA0005/5-ai-agents/readme.md
  docs/ref-arch/RA0005/6-agents-structured-data/readme.md
Labels: ready for review, bug-fix

#498 fix: remove requirement to deploy specific models in SAP AI Core for cline
  docs/ref-arch/RA0005/10-vibe-code-with-cline/readme.md
Labels: ready for review

#510 Fix typo
  docs/ref-arch/RA0014/readme.md
Labels: ready for review

#517 Add IAM-Joule-architecture
  docs/ref-arch/RA0019/4-Joule IAM/drawio/public-sap-iam-joule-sd-authn.drawio
  docs/ref-arch/RA0019/4-Joule IAM/drawio/public-sap-iam-joule-sd-authz.drawio
  docs/ref-arch/RA0019/4-Joule IAM/drawio/public-sap-iam-joule-sd-cdm.drawio
  docs/ref-arch/RA0019/4-Joule IAM/drawio/public-sap-iam-joule-sd-user.drawio
  docs/ref-arch/RA0019/4-Joule IAM/drawio/public-sap-iam-joule-sd.drawio
  docs/ref-arch/RA0019/4-Joule IAM/readme.md
Labels: ready for review

#519 Refactor BW - BDC Content
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-approach-1.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-approach-2.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-approach-3.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-bdc-detailed.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-transformations.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/migration-pathways.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/readme.md
  docs/ref-arch/RA0013/5-sap-databricks-in-business-data-cloud/readme.md
Labels: ready for review, reference-architecture

#507 Impl. of trusted tec partners section - deleted not used banners
  docs/ref-arch/RA0003/fedml-databricks/readme.md
  docs/ref-arch/RA0003/fedml-gcp/readme.md
  docs/ref-arch/RA0003/fedml-nvidia/readme.md
  docs/ref-arch/RA0003/fedml-watsonx/readme.md
  docs/ref-arch/RA0004/1-aws-data-integration/readme.md
  docs/ref-arch/RA0004/3-databricks-data-integration/readme.md
  docs/ref-arch/RA0004/4-gcp-data-integration/readme.md
  docs/tags.yml
  src/components/ReactCarousel/ReactCarousel.module.css
  src/components/SidebarFilters/SidebarFilters.js
  src/constant/tagsMapping.json
  src/pages/index.tsx
  src/sections/AdditionalResSection.tsx
  src/sections/TrustedTecPartnersSection.module.css
  src/sections/TrustedTecPartnersSection.tsx
  src/store/sidebar-store.ts
  src/theme/DocSidebar/index.tsx
  static/img/landingPage/AC_amazon_logo_dark.webp
  static/img/landingPage/AC_amazon_logo_light.webp
  static/img/landingPage/AC_databricks_logo_dark.webp
  static/img/landingPage/AC_databricks_logo_light.webp
  static/img/landingPage/AC_google_logo.webp
  static/img/landingPage/AC_ibm_logo.webp
  static/img/landingPage/AC_microsoft_logo.webp
  static/img/landingPage/AC_nvidia_logo_dark.webp
  static/img/landingPage/AC_nvidia_logo_light.webp
  static/img/landingPage/_architecture_center_hero_banner_1440x424_light.webp
  static/img/landingPage/_architecture_validator_hero_banner_1140x424_light.webp
  static/img/landingPage/_community_of_practice_hero_banner_1140x424_light.webp
  static/img/landingPage/_solution_diagram_guidelines_hero_banner_1140x424_light.webp
  static/img/landingPage/_whats_new_hero_banner_1140x424_light.webp
  static/img/landingPage/architecture_center_banner5_rounded_1200x353_dark.webp
  static/img/landingPage/architecture_center_banner5_rounded_1200x353_light.webp
  static/img/landingPage/architecture_center_banner5_rounded_1440x424_dark.webp
  static/img/landingPage/architecture_center_banner5_rounded_1440x424_light.webp
  static/img/landingPage/architecture_center_banner5_rounded_700x206_dark.webp
  static/img/landingPage/architecture_center_banner5_rounded_700x206_light.webp
  static/img/landingPage/community_puzzle_dark_150.webp
  static/img/landingPage/community_puzzle_dark_300.webp
  static/img/landingPage/community_puzzle_dark_500.webp
  static/img/landingPage/community_puzzle_light_150.webp
  static/img/landingPage/community_puzzle_light_300.webp
  static/img/landingPage/community_puzzle_light_500.webp
  static/img/landingPage/worldmap_1440x424_dark.webp
  static/img/landingPage/worldmap_1440x424_light.webp
Labels: change requested, Version 2

#529 Updated export script
  src/_scripts/_export-drawios.js
Labels: ready for review, bug-fix
