Repository SAP/architecture-center, pull requests merged in 2025-05, with the labels that each got.

#322 Patch- General Updates
  blog/2025-05-15-announcing-the-launch-of-sap-architecture-center.md
  blog/images/architecture-center-vision-2.png
  blog/images/architecture-center-vision.png
  docusaurus.config.ts
  package-lock.json
  package.json
Labels: bug-fix

#323 Fix on markdown file
  docs/ref-arch/RA0014/readme.md
  src/css/custom.css
Labels: bug-fix

#328 [PATCH] remove titles and flow tables from solution diagrams
  docs/ref-arch/RA0015/drawio/business-to-government-integration.drawio
  docs/ref-arch/RA0017/drawio/master-data-integration.drawio
  docs/ref-arch/RA0018/drawio/integrate-and-extend-with-sap-build-process-automation.drawio
Labels: ready for review, reference-architecture

#335 Fix blog and dummy architecture
  blog/2025-05-15-announcing-the-launch-of-sap-architecture-center.md
  docs/ref-arch/RA0000/readme.md
  package-lock.json
  package.json
Labels: ready for review, bug-fix

#342 optimize seo for landing page
  docusaurus.config.ts
  src/pages/index.tsx
Labels: ready for review

#345 Delete sitemap.xml from PR site build
  .github/workflows/pr-site-build.yml
Labels: ready for review, bug-fix

#351 Update RA0017 readme.md for date
  docs/ref-arch/RA0017/readme.md
Labels: bug-fix

#348 Fix display docs unlisted false
  docs/ref-arch/RA0000/readme.md
  src/_scripts/_viewPointsIndex.js
Labels: ready for review, bug-fix

#350 updates on title and image for generated pages (domains and partners)
  src/_scripts/_generatedIndexCategories.json
Labels: bug-fix

#354 updated draw.io
  docs/ref-arch/RA0005/8-agent2agent-interoperability/drawio/a2a-ard-l1.drawio
  docs/ref-arch/RA0005/8-agent2agent-interoperability/readme.md
Labels: do not merge

#353 refactor SAP BDC and Intelligent Application usage
  community/Guidelines/diagrams.md
  docs/ref-arch/RA0013/1-data-products-in-sap-business-data-cloud/drawio/bdc-dataproduct1.drawio
  docs/ref-arch/RA0013/1-data-products-in-sap-business-data-cloud/readme.md
  docs/ref-arch/RA0013/2-intelligent-applications-by-sap/readme.md
  docs/ref-arch/RA0013/3-intelligent-applications-greenfield-bdc/drawio/sap-managed-custom-intelligent-application.drawio
  docs/ref-arch/RA0013/3-intelligent-applications-greenfield-bdc/drawio/sap-managed-intelligent-application.drawio
  docs/ref-arch/RA0013/3-intelligent-applications-greenfield-bdc/readme.md
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bw-bdc-detailed.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/drawio/bwpce-sapbdc.drawio
  docs/ref-arch/RA0013/4-modernizing-sap-bw-with-sap-bdc/readme.md
  docs/ref-arch/RA0013/5-sap-databricks-in-business-data-cloud/readme.md
  docs/ref-arch/RA0013/readme.md
Labels: ready for review, reference-architecture

#355 basic front matter desc for community
  community/Guidelines/components.md
  community/Guidelines/content-structure.md
  community/Guidelines/contribution.md
  community/Guidelines/diagrams.md
  community/Guidelines/front-matter.md
  community/Guidelines/get-started.md
  community/Guidelines/the-team.md
  community/code-of-conduct.md
  community/intro.md
Labels: ready for review

#361 Minor fixes in RA0005
  docs/ref-arch/RA0005/5-ai-agents/readme.md
  docs/ref-arch/RA0005/readme.md
Labels: ready for review, reference-architecture

#358 [BUG] Update page title and metadata for Home component
  src/pages/index.tsx
Labels: ready for review

#362 Second try to do a PR for the Url fix
  src/_scripts/_export-drawios.js
Labels: ready for review, bug-fix

#364 footerfix
  .editorconfig
  community/Guidelines/contribution.md
  docusaurus.config.ts
  package.json
Labels: ready for review

#365 add robots.txt with link to sitemap and rudimentary exclusions
  docusaurus.config.ts
  static/robots.txt
Labels: enhancement, ready for review

#371 DEV -> MAIN for v1.2522.1
  .editorconfig
  README.md
  community/Guidelines/contribution.md
  docusaurus.config.ts
  package-lock.json
  package.json
  static/robots.txt
Labels: new release

#375 Potential fix for code scanning alert no. 2202: Expression injection in Actions
  .github/workflows/pr-site-build.yml
Labels: security

#376 Remove robots.txt from PR build for better SEO
  .github/workflows/pr-site-build.yml
Labels: ready for review

#377 Potential fix for code scanning alert: Workflow does not contain permissions
  .github/workflows/build-main.yml
  .github/workflows/deploy-manual.yml
  .github/workflows/find-unreferenced-files.yml
  .github/workflows/reuse-check.yml
Labels: ready for review, security
