Repository SAP/architecture-center, pull requests merged in 2025-08, with the labels that each got.

#451 Release v1.2532.1
  blog/2025-05-15-announcing-the-launch-of-sap-architecture-center.md
  blog/2025-08-12-whats-new-in-sap-architecture-center.md
  blog/authors.yml
  community/Guidelines/Development/_category_.json
  community/Guidelines/Development/design-and-styling.md
  community/Guidelines/Development/readme.md
  community/privacy.md
  community/the-team.md
  docs/ref-arch/RA0005/3-retrieval-augmented-generation/readme.md
  docs/ref-arch/RA0018/readme.md
  docusaurus.config.ts
  package-lock.json
  package.json
  src/components/TeamProfileCards/index.tsx
  src/pages/index.tsx
Labels: new release

#455 Updating release-v2 branch with dev
  blog/2025-05-15-announcing-the-launch-of-sap-architecture-center.md
  blog/2025-08-12-whats-new-in-sap-architecture-center.md
  blog/authors.yml
  community/Guidelines/Development/_category_.json
  community/Guidelines/Development/design-and-styling.md
  community/Guidelines/Development/readme.md
  community/privacy.md
  community/the-team.md
  docs/ref-arch/RA0005/3-retrieval-augmented-generation/readme.md
  docs/ref-arch/RA0018/readme.md
  docusaurus.config.ts
  package-lock.json
  package.json
  src/components/TeamProfileCards/index.tsx
  src/pages/index.tsx
  static/img/favicon.ico
  static/img/old_favicon.ico
Labels: ready for review

#453 Adjusted the watermark size
  src/_scripts/_export-drawios.js
Labels: ready for review, improvement

#461 Minor CSS fix for doc cards + React crousel responsive fix
  src/components/ReactCarousel/index.tsx
  src/css/custom.css
  src/sections/ExploreArchitectureSection.tsx
  src/theme/DocCard/styles.module.css
Labels: ready for review, bug-fix
