Repository SAP/architecture-center, pull requests merged in 2025-06, with the labels that each got.

#379 Add google site verification HTML file
  static/google8258cec0cc711949.html
Labels: ready for review

#384 v1.2523.3
  .github/workflows/deploy-manual.yml
Labels: new release

#391 Upgrade docusaurus v3.7.0 -> v3.8.1
  package-lock.json
  package.json
Labels: version-upgrade

#383 New RA: DevOps with SAP BTP
  docs/ref-arch/RA0023/drawio/devops-with-sap-btp.drawio
  docs/ref-arch/RA0023/readme.md
  package-lock.json
Labels: ready for review, reference-architecture

#399 Front matter and minor content updates for RA0024
  docs/ref-arch/RA0024/drawio/joule-studio-ref-arch.drawio
  docs/ref-arch/RA0024/readme.md
Labels: ready for review, reference-architecture

#401 adding partner models sub page under Generative AI on SAP BTP
  docs/ref-arch/RA0005/9-partner-models/drawio/ibm-granite-rag-ard.drawio
  docs/ref-arch/RA0005/9-partner-models/readme.md
Labels: ready for review, reference-architecture
