Repository SAP/architecture-center, pull requests merged in 2025-07, with the labels that each got.

#413 Joule Studio RA
  docs/ref-arch/RA0024/drawio/joule-studio-ref-arch.drawio
  docs/ref-arch/RA0024/readme.md
Labels: ready for review, reference-architecture

#417 Adding Privacy Statement
  community/privacy.md
  docusaurus.config.ts
Labels: ready for review

#421 React hydration and DrawioResources bugs
  src/components/DrawioResources.jsx
  src/sections/ExploreArchitectureSection.tsx
Labels: ready for review

#435 Content genai cline
  docs/ref-arch/RA0005/10-vibe-code-with-cline/drawio/cline-vibe-code-diagram.drawio
  docs/ref-arch/RA0005/10-vibe-code-with-cline/readme.md
Labels: ready for review, reference-architecture

#436 Release v1.2529.1
  docs/ref-arch/RA0005/10-vibe-code-with-cline/drawio/cline-vibe-code-diagram.drawio
  docs/ref-arch/RA0005/10-vibe-code-with-cline/readme.md
  docs/ref-arch/RA0005/readme.md
  package-lock.json
  package.json
Labels: new release
